version: "3.9"
services:
  db:
    image: mysql:8.0.31
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"

    ports:
      - 33060:3306
    volumes: 
      - ${HOME}/mysql:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
    networks:
      - myweb

  redis:
    image: redis:7.0.5
    container_name: redis7
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 6379:6379
    volumes:
      - ${HOME}/redis:/var/lib/redis
    command:
      --requirepass "123456"
      --appendonly yes
    networks:
      - myweb

networks:
  myweb:
    driver: bridge
