
### comyui3d
```yaml
services:
  comfy3d-pt25:
    image: yanwk/comfyui-boot:comfy3d-pt25-20250217
    container_name: comfy3d-pt25
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 28883:8188
    volumes:
      - /vol2/1000/ComfyUI/DockerAppsData/comfyui3d-pt25/root:/root
      - /vol2/1000/ComfyUI/DockerAppsData/comfyui3d-pt25/tmp:/tmp
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      PIP_INDEX_URL: "https://mirrors.cernet.edu.cn/pypi/web/simple"
      HF_ENDPOINT: "https://hf-mirror.com"
      CLI_ARGS: ""
      # 挂代理 方便下载无法下载的文件。之后可以在容器环境删除这个配置
      http_proxy: "http://192.168.1.130:7890"
      https_proxy: "http://192.168.1.130:7890"

```

### comyui-megapak
```yaml
services:
  comfyui-cu124-megapak:
    image: yanwk/comfyui-boot:cu124-megapak-20250317
    container_name: comfyui-cu124-megapak
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 28884:8188
    volumes:
      - /vol2/1000/Comfyui/comfyui-megapak:/root
      - /vol2/1000/Comfyui/all_models:/root/Comfyui/models # 如果有多个容器，使用同一文件夹下的模型
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      CLI_ARGS: ""
      PIP_INDEX_URL: "https://mirrors.cernet.edu.cn/pypi/web/simple"
      HF_ENDPOINT: "https://hf-mirror.com"

```

